# Trivial rule exists here simply as a way to trigger WORKSPACE loading.
java_library(
    name = "hello",
    srcs = ["Hello.java"],
    deps = [
        "@maven_grpc//:compile",
        "@maven_protobuf//:compile",
    ],
)
