load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# Note: This is a utility workspace (probably does not belong in
# tests) to help compute the transitive deps of grpc-java.

http_archive(
    name = "org_pubref_rules_maven",
    url = "https://github.com/pubref/rules_maven/archive/25214e11ef391bd2dc08cad3a5637ceac93b0769.zip",
    sha256 = "8bbb374af3971fa8be2a853c9d37d148cde76186ce1f19833f9bb3d5c201a581",
    strip_prefix = "rules_maven-25214e11ef391bd2dc08cad3a5637ceac93b0769",
)

load("@org_pubref_rules_maven//maven:rules.bzl", "maven_repositories", "maven_repository")

maven_repositories()

maven_repository(
    name = 'maven_protobuf',
    deps = [
        'com.google.protobuf:protobuf-java:3.4.0',
    ],
    transitive_deps = [
        'b32aba0cbe737a4ca953f71688725972e3ee927c:com.google.protobuf:protobuf-java:3.4.0',
    ],
)

maven_repository(
    name = 'maven_grpc',
    deps = [
        'io.grpc:grpc-netty:1.6.1',
        'io.grpc:grpc-protobuf:1.6.1',
        'io.grpc:grpc-stub:1.6.1',
    ],
    force = [
        'com.google.protobuf:protobuf-java:3.4.0',
        'com.google.errorprone:error_prone_annotations:2.0.11',
        'io.grpc:grpc-context:1.6.1',
    ],
    transitive_deps = [
        '3760f6a6e13c8ab070aa629876cdd183614ee877:com.google.api.grpc:proto-google-common-protos:0.1.9',
        '5871fb60dc68d67da54a663c3fd636a10a532948:com.google.code.findbugs:jsr305:3.0.0',
        '751f548c85fa49f330cecbb1875893f971b33c4e:com.google.code.gson:gson:2.7',
        '3624d81fca4e93c67f43bafc222b06e1b1e3b260:com.google.errorprone:error_prone_annotations:2.0.11',
        '6ce200f6b23222af3d8abb6b6459e6c44f4bb0e9:com.google.guava:guava:19.0',
        '41614af3429573dc02645d541638929d877945a2:com.google.instrumentation:instrumentation-api:0.4.3',
        'b32aba0cbe737a4ca953f71688725972e3ee927c:com.google.protobuf:protobuf-java:3.4.0',
        '35d048270e0b2f29e7e4a45daf21d46d1b121a24:com.google.protobuf:protobuf-java-util:3.3.1',
        '9c52ae577c2dd4b8c6ac6e49c1154e1dc37d98ee:io.grpc:grpc-context:1.6.1',
        '871c934f3c7fbb477ccf2dd4c2a47a0bcc1b82a9:io.grpc:grpc-core:1.6.1',
        '6941e41b5f422da1670d5d01bf476644330b536e:io.grpc:grpc-netty:1.6.1',
        'a309df5d2627422ceb9cb08fb6a240656d75760a:io.grpc:grpc-protobuf:1.6.1',
        '124bca81a50bc76b6a6babcc4bc529e5a93db70f:io.grpc:grpc-protobuf-lite:1.6.1',
        'f32b7ad69749ab6c7be5dd21f1e520a315418790:io.grpc:grpc-stub:1.6.1',
        '71f0a707209b1356d924d6f8b2f415f8b8e1cf82:io.netty:netty-buffer:4.1.14.Final',
        'b8573ae401f17e6927f158e4c446311bf0646173:io.netty:netty-codec:4.1.14.Final',
        'f287b593a37e516f98c9dae7337303e7254e8ea1:io.netty:netty-codec-http:4.1.14.Final',
        '00d2af27befab8e1abfbf37d1ac2a5185dce1dbe:io.netty:netty-codec-http2:4.1.14.Final',
        'b8d856c686ac960b9e9b9f8f9b4083978c161327:io.netty:netty-codec-socks:4.1.14.Final',
        '230ff063651295d2695c0b4e9411e22bbbb9c09d:io.netty:netty-common:4.1.14.Final',
        '626a48b846736c944eb35dd9b0fe0435b76ebf93:io.netty:netty-handler:4.1.14.Final',
        '9dbedd6cc6ab9299c927d0c73791d3d8fd76ac20:io.netty:netty-handler-proxy:4.1.14.Final',
        'f91e0197522e7d33fce84b3dfd86ade15edb0006:io.netty:netty-resolver:4.1.14.Final',
        '3ed6474f1289635fc0696ec37380e20f258950a2:io.netty:netty-transport:4.1.14.Final',
        'cbd0a716a7d85ac34b83d86b13f0a6655e45c2ba:io.opencensus:opencensus-api:0.5.1',
    ],
)

load("@maven_protobuf//:rules.bzl", "maven_protobuf_compile")
maven_protobuf_compile()

load("@maven_grpc//:rules.bzl", "maven_grpc_compile")
maven_grpc_compile()
