load("//bzl:deps.bzl", "require")

def deps(opts = {}):
  require("bind_third_party_protoc", opts)

  require("com_google_auth_google_auth_library_credentials", opts)
  require("com_google_code_gson_gson", opts)
  require("com_google_code_findbugs_jsr305", opts)
  require("com_google_guava_guava", opts)
  require("com_google_protobuf_protobuf_java", opts)
  require("com_google_protobuf_protobuf_java_util", opts)
  require("com_google_protobuf_nano_protobuf_javanano", opts)
  require("com_squareup_okhttp_okhttp", opts)
  require("com_squareup_okio_okio", opts)
  require("io_grpc_grpc_auth", opts)
  require("io_grpc_grpc_core", opts)
  require("io_grpc_grpc_netty", opts)
  require("io_grpc_grpc_okhttp", opts)
  require("io_grpc_grpc_protobuf", opts)
  require("io_grpc_grpc_protobuf_lite", opts)
  require("io_grpc_grpc_protobuf_nano", opts)
  require("io_grpc_grpc_stub", opts)
  require("io_netty_netty_buffer", opts)
  require("io_netty_netty_codec", opts)
  require("io_netty_netty_codec_http", opts)
  require("io_netty_netty_codec_http2", opts)
  require("io_netty_netty_common", opts)
  require("io_netty_netty_handler", opts)
  require("io_netty_netty_resolver", opts)
  require("io_netty_netty_transport", opts)
  require("protoc_gen_grpc_java_linux_x86_64", opts)
  require("protoc_gen_grpc_java_macosx", opts)
