package(default_visibility = ["//visibility:public"])

load("//protobuf:rules.bzl", "proto_dependencies")

proto_dependencies(
    name = "deps",
    languages = [
        "cpp",
    ],
    format = "markdown",
)
