load("//protobuf:internal/proto_compile.bzl", "proto_compile")
load("//protobuf:internal/proto_language.bzl", "proto_language", "proto_language_deps")
load("//protobuf:internal/proto_repositories.bzl", "proto_repositories")
load("//protobuf:internal/github_archive.bzl", "github_archive")
load("//protobuf:internal/proto_dependencies.bzl", "proto_dependencies")
