load("@org_pubref_rules_protobuf//python:rules.bzl", "py_proto_compile")

py_proto_compile(
    name = "py_options_proto",
    protos = ["models/options.proto"],
    verbose = 0,
    visibility = ["//visibility:public"],
    with_grpc = False,
)
