package(default_visibility = ["//visibility:public"])

load("@org_pubref_rules_protobuf//go:rules.bzl", "go_proto_library")

go_proto_library(
    name = "config_go_proto",
    go_package = "pubref.org/test/app",
    protos = ["config.proto"],
    verbose = 0,
)
