package(default_visibility = ["//visibility:public"])

# load("//bzl:python/rules.bzl", "py_proto_library")

# py_proto_library(
#     name = "protos",
#     protos = ["//examples/helloworld/proto:helloworld.proto"],
#     verbose = 1,
#     with_grpc = False,
# )

# py_protobuf_generate(
#     name = "client",
#     srcs = [
#         "client.py",
#         ":proto",
#     ],
# )
