package(default_visibility = ["//visibility:public"])

load("//protobuf:rules.bzl", "proto_language")

proto_language(
    name = "python",
    pb_file_extensions = ["_pb2.py"],
    pb_compile_deps = [
    ],
    supports_grpc = False,
)
