package(default_visibility = ["//visibility:public"])

load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_test")
load(
    "//bzl:go/class.bzl",
    GO = "CLASS",
)

# go_binary(
#     name = "greeter",
#     srcs = [
#         "greeter.go",
#     ],
#     deps = [
#         "//examples/helloworld/proto:gw",
#         "@com_github_golang_glog//:go_default_library",
#         "@com_github_grpc_ecosystem_grpc_gateway//:runtime",
#         "@org_golang_google_grpc//:go_default_library",
#         "@org_golang_x_net//:context",
#     ],
# )

# go_test(
#     name = "greeter_test",
#     size = "small",
#     srcs = [
#         "greeter.go",
#         "greeter_test.go",
#     ],
#     deps = [
#         "//examples/helloworld/go/server:greeter",
#         "//examples/helloworld/proto:go",
#         "//examples/helloworld/proto:gw",
#         "@com_github_golang_glog//:go_default_library",
#         "@com_github_golang_protobuf//:jsonpb",
#         "@com_github_grpc_ecosystem_grpc_gateway//:runtime",
#         "@org_golang_google_grpc//:go_default_library",
#         "@org_golang_x_net//:context",
#     ],
# )
